<html>
<head>
<title>
Hamdy Elattar 
</title>
</head>

<body bgcolor="blue"
text="red"
font face="segoe script">
<h2> This My java script code </h2>
<hr>
<script language="javascript">
<!--
           document.write("Hello and Welcome")
           document.write("<p>")
           document.write("All years and you`re fine")
           document.write("<p>")
           document.write("Your brother : Eng : Hamdy Elattar")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("سبحان الله")
           alert("لا اله الا الله ... محمد رسول الله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("الحمد لله")
           alert("لا اله الا الله ... محمد رسول الله")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("الله أكبر")
           alert("لا اله الا الله ... محمد رسول الله")
           confirm("أخوكم : حمدي العطار <p> هل استمتعتم ..؟ <p> IT Specialist
//-->
</script>
</body>
</html>
